Vesit_Hacks_21/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.mainIndex, name='main_index'),
    path('dashboard/', include('dashboard.urls')),
    path('events/', include('events.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views

app_name='dashboard'

urlpatterns = [
    path('',views.index,name='index'),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('profile/', views.profile, name="profile"),
    path('uploadProfilePic/', views.uploadProfilePic, name="upload_profile_pic")
]

events/urls.py
from django.urls import path
from . import views

app_name='events'

urlpatterns = [
    path('', views.index,name='index'),
    path('AddEvent/', views.addEvent, name='add_event'),
    path('StoreEvent/', views.storeEvent, name='store_event'),
    path('EventDetail/<int:id>', views.eventDetail, name='event_detail'),
    path('ApproveEvent', views.approveEvent, name='approve_event'),
    path('Approve/<int:id>', views.approve, name="approve"),
    path('Reject/<int:id>', views.reject, name="reject"),
    path('previousevents/',views.previousEvents,name='previous_events'),
    path('ongoingevents/',views.onGoingEvents,name='ongoing_events'),
    path('Storephotos/<int:id>',views.Storephotos,name='store_photos'),
]

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <style>
      a {
        color: white;
      }

      .navbar {
        display: 'block';
        z-index: 4;
      }
      .navbar-brand {
        font-family: 'Microsoft Sans Serif';
        font-weight: bold;
        font-size: 20px;
        width: 70px;
      }
      .btn-style {
        border: 2px solid #009bd9;
        border-radius: 30px;
        color: white;
      }
      .btn-style:hover {
        background: white;
        color: black;
      }
      a:hover{
        color: white;
        text-decoration: underline;
      }

      .active{
        border-bottom: 3px solid white;
      }

      .content {
        padding: 16px;
      }

      .sticky {
        position: fixed;
        top: 0;
        width: 100%;
      }

      .sticky + .content {
        padding-top: 60px;
      }
      </style>
      {% block head %}
      {% endblock head %}  
    <title>{% block title %} {% endblock title %}</title>
  </head>
  <body>
    {% block aboveNavBar %}
    
    {% endblock aboveNavBar %}
    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg" id="navbar" style="background: #36517e; color: white;">
        <a class="navbar-brand my-3" href="/">VESIT</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% block homeActive %} {% endblock %}">
              <a class="nav-link" href="/events/">Home<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% block upcomingActive %} {% endblock %}">
              <a class="nav-link" href="/events/">Upcoming Events<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% block ongoingActive %} {% endblock %}">
              <a class="nav-link" href="/events/ongoingevents">Ongoing Events<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% block previousActive %} {% endblock %}">
              <a class="nav-link" href="/events/previousevents">Previous Events</a>
            </li>
          </ul>
          {% if request.session.is_authenticated and request.session.is_priviledged %}
            <a href="/events/ApproveEvent" class="nav-link {% block activeApproval %}{% endblock activeApproval %}"> Approvals </a>
          {% endif %}
          {% if request.session.is_authenticated %}
            <!-- Example single danger button -->
            <div class="btn-group">
              <button type="button" class="btn btn-primary dropdown-toggle ml-2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Welcome {{ request.session.user_fname }}
              </button>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'dashboard:profile' %}">Profile</a>
                <a class="dropdown-item" href="{% url 'dashboard:logout' %}">Logout</a>
              </div>
            </div>
          {% else %}
            <button type="button" class="btn btn-style mr-2 " data-toggle="modal" data-target="#loginModal">
              Log in
            </button>
          {% endif %}
        </div>
      </nav>

      <!-- Login Modal -->
      <!-- LoginModal -->
      <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModal" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="loginModal">Login</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <form action="{% url 'dashboard:login' %}" method="POST"> 
              {% csrf_token %}
                <div class="form-group">
                  <label for="username">Email</label>
                  <input type="text" class="form-control" id="username" name="useremail" required>
                </div>
                <div class="form-group">
                  <label for="pass1">Password</label>
                  <input type="password" class="form-control" id="pass1" name="password" required>
                </div>
                  <button type="submit" class="btn btn-primary">Log in</button>
            </form>
            </div>
            
          </div>
        </div>
      </div>

    <!-- Optional JavaScript; choose one of the two! -->

    {% block body %}

    {% endblock body %}
    <script>
    window.onscroll = function() {myFunction()};

    var navbar = document.getElementById("navbar");
    var sticky = navbar.offsetTop;

    function myFunction() {
      if (window.pageYOffset >= sticky) {
        navbar.classList.add("sticky")
      } else {
        navbar.classList.remove("sticky");
      }
    }
    </script>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    {% comment %} <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script> {% endcomment %}

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block homeActive %}active{% endblock homeActive %}
{% block head %}
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <style>
        body {
            margin: 0;
        }
        .upper-block {
            background: #36517e;
            color: white;
            text-align: center;
            font-family: 'Microsoft Sans Serif';
            height: 90vh;
            margin-top: auto;
            margin-bottom: auto;
        }
        .com-name {
            text-align: center;
            font-family: 'Lucida Handwriting';
            font-weight: bold;
            font-size: 7vh;
        }
        .heading-text {
            padding-top: 2%;
        }
        .my-card {
            border-radius: 40px;
            margin-bottom: 5vh;
            margin-top: 5vh;
        }
        .my-card-text {
            font-family: 'Lucida Sans Typewriter';
            margin: auto;
            font-weight: bold;
        }
    </style>
{% endblock head %}
{% block aboveNavBar %}
    <div class="container-fluid upper-block">
        <h1 class="align-middle heading-text" data-aos="fade-down"> VES Events </h1>
        <m data-aos-delay= "300" data-aos="zoom-in" data-aos-easing="ease">
            <img class="img-fluid" src="{% static 'img/VESIT_LOGO.png' %} "  style="width: 50vh; object-fit: contain;" /> 
        </m>
    </div>
{% endblock aboveNavBar %}

{% block body %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-2 com-name mx-4">
                E-Cell
            </div>
            <div class="col-sm-2 com-name">
                IIC
            </div>
            <div class="col-sm-2 com-name">
                CSI
            </div>
            <div class="col-sm-2 com-name">
                IEEE
            </div>
            <div class="col-sm-2 com-name">
                ISTE
            </div>
        </div>
    </div>
    <div class="container-fluid my-2" style="padding: 3% 10%">
            <!-- Card -->
                <div data-aos="fade-left" data-aos-duration="1000" class="row mx-2 p-2 my-card shadow-lg bg-white-rounded">
                    <div class="col-sm-6" >
                        <img src="{% static 'img/sample_events_logo.jpg' %}" style="width: 40vh; object-fit: contain; border-radius: 5vh;" />
                    </div>
                    <div class="col-sm-6 my-card-text">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt adipisci tempora amet eaque, expedita ab nemo vel culpa. Placeat sapiente nobis, itaque a eius dignissimos cumque quas ducimus fuga saepe.
                    </div>
                </div>
            <!-- Card End -->
                <div data-aos="fade-right" data-aos-duration="1000" class="row mx-2 p-2 my-card shadow-lg bg-white-rounded">
                    <div class="col-sm-6" >
                        <img src="{% static 'img/sample_events_logo.jpg' %}" style="width: 40vh; object-fit: contain; border-radius: 5vh;" />
                    </div>
                    <div class="col-sm-6 my-card-text">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt adipisci tempora amet eaque, expedita ab nemo vel culpa. Placeat sapiente nobis, itaque a eius dignissimos cumque quas ducimus fuga saepe.
                    </div>
                </div>
                <div data-aos="fade-left" data-aos-duration="1000" class="row mx-2 p-2 my-card shadow-lg bg-white-rounded">
                    <div class="col-sm-6" >
                        <img src="{% static 'img/sample_events_logo.jpg' %}" style="width: 40vh; object-fit: contain; border-radius: 5vh;" />
                    </div>
                    <div class="col-sm-6 my-card-text">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt adipisci tempora amet eaque, expedita ab nemo vel culpa. Placeat sapiente nobis, itaque a eius dignissimos cumque quas ducimus fuga saepe.
                    </div>
                </div>
    </div>

    <!-- AOS Scripts-->
    <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
    <script>
        AOS.init();
    </script>
{% endblock body %}