Vesit_Hacks_21/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.mainIndex, name='main_index'),
    path('dashboard/', include('dashboard.urls')),
    path('events/', include('events.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

events/urls.py
from django.urls import path
from . import views

app_name='events'

urlpatterns = [
    path('', views.index,name='index'),
    path('AddEvent/', views.addEvent, name='add_event'),
    path('StoreEvent/', views.storeEvent, name='store_event'),
    path('EventDetail/<int:id>', views.eventDetail, name='event_detail'),
    path('ApproveEvent', views.approveEvent, name='approve_event'),
    path('Approve/<int:id>', views.approve, name="approve"),
    path('Reject/<int:id>', views.reject, name="reject"),
    path('previousevents/',views.previousEvents,name='previous_events'),
    path('ongoingevents/',views.onGoingEvents,name='ongoing_events'),
    path('Storephotos/<int:id>',views.Storephotos,name='store_photos'),
]

events/models.py
from django.db import models
from college import models as mod
# Create your models here.
class Event(models.Model):

    event_title = models.CharField(max_length = 50, default="")
    event_description = models.CharField(max_length = 500)
    # event_start
    event_time = models.TimeField()
    event_date = models.DateField()
    # event_end
    end_time = models.TimeField()
    end_date = models.DateField()
    #organizer:
    is_student = models.BooleanField() # True: STUDENT, False: STAFF
    # registration_link
    registration_link = models.CharField(max_length = 100)
    # postor
    postor = models.ImageField(upload_to = 'Events/Postors', default="")
    #Foreign Keys

    event_place = models.ForeignKey(mod.Place, on_delete=models.CASCADE,null=True,blank=True)


    dept_id = models.ForeignKey(mod.Department,on_delete=models.CASCADE,null=True,blank=True)
    approval_id  = models.ForeignKey(mod.Staff,on_delete=models.CASCADE,null=True,blank=True)
    event_type = models.IntegerField()
    committee_id = models.ForeignKey(mod.Committee, on_delete=models.CASCADE,null=True,blank=True  )
    status = models.IntegerField()
    #setting conductor id
    conductor_id=None
    if(is_student):
        conductor_id = models.ForeignKey(mod.Student,on_delete=models.CASCADE,null=True,blank=True)
    else:
        conductor_id = models.ForeignKey(mod.Staff,on_delete=models.CASCADE,null=True,blank=True)

    def __str__(self):
        return self.event_title

class EventPhoto(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    photo = models.ImageField( upload_to='Events/EventPhotos')

    def __str__(self):
        return self.event.event_title
    

events/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Event,EventPhoto
from college.models import *
from datetime import datetime,date,time


# Create your views here.
def index(request):
    context={}
    today = datetime.today().strftime('%Y-%m-%d %H:%M:%S')
    today_date,today_time = today.split(' ')
    hour,month,seconds = today_time.split(':')
    today_time = datetime.strptime(today_time,'%H:%M:%S').time()
    events = Event.objects.all().filter()
    today_date = date.today()
    # today_time= time.isoformat(timespec='auto')

    previous_events = Event.objects.all().filter(event_date__lt = today_date)
    upcoming_events = Event.objects.all().filter(event_date__gt = today_date,status=1)
    ongoing_events = Event.objects.all().filter(event_date__lte = today_date , end_date__gte = today_date)


    print(previous_events)
    print(upcoming_events)
    print(ongoing_events)
    context['events'] = upcoming_events
    return render(request,'events/allEvents.html',context=context)

def addEvent(request):
    places_object = Place.objects.all()
    places=[]
    context={}
    for place in places_object:
        places.append(place)
    print(places)
    context['places']=places

    return render(request, 'events/add_events.html',context=context)

def storeEvent(request):
    # print(request.POST)
    if(request.method == 'POST'):
        print(request.POST)
        event = Event()
        # Event details
        event.event_title = request.POST['title']
        event.event_description = request.POST['description']
        event.event_time = request.POST['start_time']
        event.event_date = request.POST['start_date']
        event.end_time = request.POST['end_time']
        event.end_date = request.POST['end_date']

        # organizer
        event.is_student=True
        is_student = request.POST['organizer']
        if(is_student == 1):
            event.is_student=False
            event.conductor_id = Staff.objects.get(staff_id = request.session['user_id'])
        else:
            event.conductor_id = Student.objects.get(student_id = request.session['user_id'])
        if request.FILES['filename']:
            event.postor = request.FILES['filename']
        event.registration_link = request.POST['registration']
        place_name = request.POST['place']

        event.event_place = Place.objects.get(place_name=place_name)
        event.event_type = int(request.POST['level'])
        print(request.session['dept_id'])
        dept_id = int(request.session['dept_id'])
        dept_object = Department.objects.get(dept_id = dept_id)
        event.dept_id = dept_object
        event.status = 0
        event.save()

    return redirect('/events')

def eventDetail(request, id):
    today_date = date.today()
    event = Event.objects.get(id=id)
    photos = None
    if event.event_date < today_date:
       photos = EventPhoto.objects.all().filter(event=event)
    context = {
        'event_id':id,
        'event_title': event.event_title,
        'event_description': event.event_description,
        'registration_link': event.registration_link,
        'start_date' : event.event_date,
        'start_time' : event.event_time,
        'end_date' : event.end_date,
        'cond_id' : event.conductor_id,
        'end_time' : event.end_time,
        'event_place' : event.event_place,
        'event_postor': event.postor,
        'is_this_previous': True if event.event_date < today_date else False,
        'photos' : photos
    }
    print(context)
    return render(request, 'events/eventDetails.html', context)


  

def previousEvents(request):
    context = {}
    today_date = date.today()
    previous_events = Event.objects.all().filter(end_date__lt=today_date,status=1) 
    context['events'] = previous_events
    context['status'] = 'previous'
    return render(request,'events/previousEvents.html',context=context)

def onGoingEvents(request):
    context={}
    today_date = date.today()
    ongoing_events = Event.objects.all().filter(event_date__lte=today_date, end_date__gte=today_date,status=1)
    context['events']=ongoing_events
    return render(request,'events/ongoing.html',context=context)

def approveEvent(request):
    # status: 0 ---> Pending
    # status: 1 ---> Accept
    # status: 2 ---> Rejected
    staff_type = request.session['Staff_type']
    context = {}
    print('Approve Event--------------', staff_type)
    if staff_type > 0:
        if staff_type == 3:
            pending_approvals = Event.objects.all().filter(status=0, event_type = staff_type)
            accepted_approvals = Event.objects.all().filter(status=1, event_type = staff_type)
            rejected_approvals = Event.objects.all().filter(status=2, event_type = staff_type)
            context = {
                        'pending_approvals': pending_approvals,
                        'accepted_approvals': accepted_approvals,
                        'rejected_approvals': rejected_approvals
                        }
        else:
            dept_object = Department.objects.get(dept_id = request.session['dept_id'])
            pending_approvals = Event.objects.all().filter(status=0, event_type = staff_type, dept_id = dept_object)
            accepted_approvals = Event.objects.all().filter(status=1, event_type = staff_type, dept_id = dept_object)
            rejected_approvals = Event.objects.all().filter(status=2, event_type = staff_type, dept_id = dept_object)
            context = {
                        'pending_approvals': pending_approvals,
                        'accepted_approvals': accepted_approvals,
                        'rejected_approvals': rejected_approvals
                        }
    
    conductor_object = None
    if request.session['is_student']:
        conductor_object = Student.objects.get(student_id = request.session['user_id'])
    else:
        conductor_object = Staff.objects.get(staff_id = request.session['user_id'])

    # yourPendingApprovals = Event.objects.all().filter(status = 0, conductor_id=conductor_object)
    context['yourPendingApprovals'] = None
    print(context)
    return render(request, 'events/give_approval.html', context)

def approve(request, id):
    print('Approval ---- ', id)
    event_object = Event.objects.get(id=id, status=0)
    event_object.status = 1

    user_id = request.session['user_id']
    event_object.approval_id = Staff.objects.get(staff_id = user_id)
    event_object.save(update_fields = ['status', 'approval_id'])
    return redirect('/events/ApproveEvent')

def reject(request, id):
    print('Approval ---- ', id)
    event_object = Event.objects.get(id=id, status=0)
    event_object.status = 2

    user_id = request.session['user_id']
    event_object.approval_id = Staff.objects.get(staff_id = user_id)
    event_object.save(update_fields = ['status', 'approval_id'])
    return redirect('/events/ApproveEvent')

def Storephotos(request,id):
    print(request.FILES['photos'])
    event = Event.objects.all().filter(id=id)[0]
    # print(event)
    
    eventphoto = EventPhoto()
    eventphoto.event = event
    eventphoto.photo = request.FILES['photos']
    eventphoto.save()
    return redirect('/events/EventDetail/' + str(id))

templates/events/add_events.html
{% extends 'base.html' %}

{% block head %}
  <!-- CDN -->
  <script
    type="text/javascript"
    src='https://cdn.tiny.cloud/1/no-api-key/tinymce/5/tinymce.min.js'
    referrerpolicy="origin">
  </script>

  <style>
    textarea.tinyMCE {
        width: 100% !important;
    }

    @media only screen and (min-width: 600px) {
        textarea.richEditor {
            width: 600px !important;
        }
    }
  </style>

  <!-- API CALL -->
  <script type="text/javascript">
  tinymce.init({
    selector: '#description',
    height: 300,
    plugins: [
      'advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker',
      'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
      'table emoticons template paste help'
    ],
    toolbar: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | ' +
      'bullist numlist outdent indent | link image | print preview media fullpage | ' +
      'forecolor backcolor emoticons | help',
    menu: {
      favs: {title: 'My Favorites', items: 'code visualaid | searchreplace | spellchecker | emoticons'}
    },
    menubar: 'favs file edit view insert format tools table help',
    content_css: 'css/content.css'
  });
  </script>
{% endblock head %}

{% block body %}

    <div class="container" style="padding-bottom:50px;">
        <h1> Add Events </h1>
        <form action='/events/StoreEvent/' method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="mb-3">
                <h4><label for="Title" class="form-label">Title</label></h4>
                <input type="text" class="form-control" id="Title" name="title">
            </div>
            <div class="mb-3">
                <h4><label for="Title" class="form-label">Description</label></h4>
                <textarea id="description" name="description" cols="100"></textarea>
            </div>

            <!-- Schedule -->
            <br />
            <div class="container">
                <div class="row">
                    <div class="col-sm">
                        <h4> Start of event </h4>
                        <div class="mb-3">
                            <label for="start_date" class="form-label">Start Date</label>
                            <input type="date" id="start_date" name="start_date" />
                        </div>
                        <div class="mb-3">
                            <label for="start_time" class="form-label">Start Time</label>
                            <input type="time" id="start_time" name="start_time" />
                        </div>
                    </div>
                    <div class="col-sm">
                        <h4> End of event </h4>
                        <div class="mb-3">
                            <label for="end_date" class="form-label">End Date</label>
                            <input type="date" id="end_date" name="end_date" />
                        </div>
                        <div class="mb-3">
                            <label for="end_time" class="form-label">End Time</label>
                      1      <input type="time" id="end_time" name="end_time" />
                        </div>
                    </div>
                </div>

                <!-- is student or faculty-->
                <br />
                <h4> Organizer </h4>
                <input type="radio" id="student" name="organizer" value="0">
                <label for="student">Student</label><br>
                <input type="radio" id="faculty" name="organizer" value="1">
                <label for="faculty">Faculty</label><br>

                <!-- Registration Link -->
                <br />
                <div class="mb-3">
                    <h4><label for="Registration" class="form-label">Registration Link</label></h4>
                    <input type="text" class="form-control" id="Registration" name="registration">
                </div>

                <!-- Upload a postor -->
                <input type="file" id="myFile" name="filename">
                <br />
                <br />


                <div class="form-group">
                  <label for="Places">Places:</label>
                  <select class="form-control" id="places" name="place">
                      {% for place in places %}
                        <option value="{{place}}">{{place}}</option>
                      {% endfor %}
                  </select>
                </div>

                <div class="form-group">
                    <label for="Event Level">Event Level</label>
                    <select class="form-control" id="places" name="level">
                        <option value="1">Student Body Event</option>
                        <option value="2">Department level Event</option>
                        <option value="3">Institute Level Event</option>
                    </select>
                </div>
                <button justify-content="center" type="submit" class="btn btn-primary">Submit</button>
            </div>
        </form>


        {% comment %} <form action='/events/StoreEvent' method="GET">
            
            <button id="bt" type="submit">submit</button>
        </form> {% endcomment %}
    </div>

    {% comment %} <script>

        $("#bt").click((event) => {
            event.preventDefault();
            alert('clicked');
            console.log(tinyMCE.get('myTextarea').getContent())
        })
    </script> {% endcomment %}
{% endblock body %}

templates/events/allEvents.html
{% extends 'base.html' %}
{% block upcomingActive %} active {% endblock upcomingActive %}
{% block head %}
<style>
  .addButton {
    float: right;
    margin-right: 10%;
    margin-bottom: 5%;
    border-radius: 40px;
    color: black;
    font-weight: bold;
    font-size: 1rem;
  }

  body {
    background-color: #eee;
  }

  .title {

    margin-bottom: 50px;
    text-transform: uppercase;
  }

  .card-block {
    font-size: 1em;
    position: relative;
    margin: 0;
    padding: 1em;
    border: none;
    border-top: 1px solid rgba(34, 36, 38, .1);
    box-shadow: none;

  }

  .card {
    font-size: 1em;
    overflow: hidden;
    padding: 5;
    border: none;
    border-radius: .28571429rem;
    box-shadow: 0 1px 3px 0 #d4d4d5, 0 0 0 1px #d4d4d5;
    margin-top: 20px;
  }

  .carousel-indicators li {
    border-radius: 12px;
    width: 12px;
    height: 12px;
    background-color: #404040;
  }

  .carousel-indicators li {
    border-radius: 12px;
    width: 12px;
    height: 12px;
    background-color: #404040;
  }

  .carousel-indicators .active {
    background-color: white;
    max-width: 12px;
    margin: 0 3px;
    height: 12px;
  }

  .carousel-control-prev-icon {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23fff' viewBox='0 0 8 8'%3E%3Cpath d='M5.25 0l-4 4 4 4 1.5-1.5-2.5-2.5 2.5-2.5-1.5-1.5z'/%3E%3C/svg%3E") !important;
  }

  .carousel-control-next-icon {
    background-image: url("data:image/svg+xml;charset=utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' fill='%23fff' viewBox='0 0 8 8'%3E%3Cpath d='M2.75 0l-1.5 1.5 2.5 2.5-2.5 2.5 1.5 1.5 4-4-4-4z'/%3E%3C/svg%3E") !important;
  }

  lex-direction: column;
  }

  .btn {
    margin-top: auto;
  }
  .card-title {
    font-family: 'Microsoft Sans Serif';
    font-size: 5vh;
    font-weight: bold;
  }
  .card-desc {
    font-size: 5vh; 
  }
</style>

{% endblock head %}

{% block body %}

{%if events %}
<div class='container-fluid row mx-auto'>
  {%for event in events %}
  <div class="card text-center mx-auto shadow-lg" style='margin:auto; margin-top:2%; width: 45%; border-radius: 20px;'>
    <div class="row">
      <div class="col-sm-5 my-auto">
        <img class="d-block w-100 mx-3" src='/media/{{event.postor}}' alt="" style="width: 20vh; border-radius: 2vh;">
      </div>
      <div class="col-sm-7">
        <div class="card-block">
          <p class="card-title">{{event.event_title}}</p>
          <p class="card-desc">{{event.event_description|safe|truncatechars:50 }}</p>
          <br>
          <br>
          <a href="/events/EventDetail/{{event.id}}" class="btn btn-primary">Know More</a>
            <a href="{{event.registration_link}}" class="btn btn-success">Register</a>
        </div>
      </div>
    </div>
  </div>
{%endfor%}
</div>
{%else%}
<h1>No events right now</h1>
{%endif%}
</div>

{% if request.session.is_authenticated and request.session.is_priviledged %}
<div class="addEvent">
  <a href="{% url 'events:add_event' %}" class="btn btn-primary addButton" type="submit">Add Event</a>
</div>
{% endif %}
{% endblock body %}

templates/events/eventDetails.html
{% extends 'base.html' %}
{% load static %}

{% block head %}

<style>
#postor {
    height: 400px;
    width: 400px;
    object-fit: contain;
    margin: auto;
}
.upload-card {
    width: 50%;

}

</style>

{% endblock head %}

{% block body %}
    <div class="fluid container my-5">
        <h3 style="text-align: center;"> {{ event_title }} </h3>
        <div class="row">
            <div class="col">
                <img id="postor" src="/media/{{ event_postor }}" alter="Postor"> </img>
            </div>
            <div class="col my-auto">
                {{ event_description|safe|truncatechars:500 }}
                <!-- Buttons -->
                <div class="container my-4">
                    <div class="row">
                        <!-- <h1>{{event_id}}</h1> -->
                        {%if is_this_previous %}
                            
                            <form enctype='multipart/form-data' method="POST" action='/events/Storephotos/{{event_id}}'>
                                <div class="col">
                                    {% csrf_token %}
                                    <input class="btn " name='photos' width='400' height="200" type='file' value='Upload Images' style='width:250px'> 
                                    <button class='btn btn-warning' type='submit' href= /events/Storephotos/{{event.id}}>Upload</button>
                                </div>
                            </form>
                            
                        {% endif %}
                        <div class="col">
                            <button class="btn btn-primary" id="know_more"> Know More </button>
                        </div>
                        {% if not is_this_previous %}
                            <div class="col">
                                <button class="btn btn-success" id="register"><a href="https://{{ registration_link }}" style="color: white; text-decoration: none;">Register </a></button>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class = "container-fluid row mx-auto text-center" style='border: 2px black; width:100%;'>
        {%if photos %}
        <h2>Event Gallery</h2>
            <div class="row my-4 mx-auto" style="text-align: center;">
                {% for photo in photos %}
                <div class="col">
                    <div class="card mx-auto shadow-lg" style="width: 60vh; border-radius: 40px;">
                        <img
                            src="/media/{{photo.photo}}"
                            class="card-img-top"
                            alt="..."
                            style="border-radius: 40px; height: 100%"
                        />
                    </div>
                </div>
                {% endfor %}
                {% comment %} <div class="col">
                    <div class="card mx-auto" style="width: 60vh; border-radius: 40px;">
                        <img
                            src="https://mdbootstrap.com/img/new/standard/city/042.jpg"
                            class="card-img-top"
                            alt="..."
                            style="border-radius: 40px;"
                        />
                    </div>
                </div>
                <div class="col">
                    <div class="card mx-auto" style="width: 60vh; border-radius: 40px;">
                        <img
                            src="https://mdbootstrap.com/img/new/standard/city/043.jpg"
                            class="card-img-top"
                            alt="..."
                            style="object-fit: contain; border-radius: 40px;"
                        />
                    </div>
                </div> {% endcomment %}
            </div>
        {% endif %}
    </div>

    <div class="container">
        <!-- Modal -->
        <div class="modal fade" id="myModal" role="dialog">
            <div class="modal-dialog">    
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title"> {{event_title}}</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <p>
                            {{ event_description|safe }}
                            <br>
                            <a> <strong>Start Date : <span class="badge badge-pill badge-success"> {{ start_date }} {{ start_time }} </span> </strong></a>
                            <br>
                            <a> <strong>End Date :  <span class="badge badge-pill badge-danger"> {{ end_date }}{{ end_time }} </span></strong> </a>
                            <br>
                            <a> <strong> Place : <span class="badge badge-pill badge-primary"> {{event_place}} </span></strong></a>

                        </p>
                    </div>
                    <div class="modal-footer">
                        {% if not is_this_previous %}
                            <button type="button" class="btn btn-success"><a href="https://{{ registration_link }}" style="color: white; text-decoration: none;">Register </a></button>
                            <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
<script>
    $("#know_more").click(function() {
        $("#myModal").modal('show');
    });
</script>
{% endblock body %}

templates/events/ongoing.html
{% extends 'base.html' %}
{% block ongoingActive %} active {% endblock ongoingActive %}
{% block head %}
  <style>
  .addButton {
    float: right;
    margin-right: 10%;
    margin-bottom: 5%;
    border-radius: 40px;
    color: black;
    font-weight: bold;
    font-size: 1rem;
  }
  body {
    background-color: #eee;
  }

  .title {

    margin-bottom: 50px;
    text-transform: uppercase;
  }

  .card-block {
    font-size: 1em;
    position: relative;
    margin: 0;
    padding: 1em;
    border: none;
    border-top: 1px solid rgba(34, 36, 38, .1);
    box-shadow: none;

  }

  .card {
    font-size: 1em;
    overflow: hidden;
    padding: 5;
    border: none;
    border-radius: .28571429rem;
    box-shadow: 0 1px 3px 0 #d4d4d5, 0 0 0 1px #d4d4d5;
    margin-top: 20px;
  }
  .card-title {
    font-family: 'Microsoft Sans Serif';
    font-size: 5vh;
    font-weight: bold;
  }
  .card-desc {
    font-size: 5vh; 
  }
  </style>

{% endblock head %}

{% block body %}

{%if events %}
<div class='container-fluid row' >
  {%for event in events %}
  <div class="card text-center mx-auto shadow-lg" style='margin:auto; margin-top:2%; width: 45%; border-radius: 20px;'>
    <div class="row">
      <div class="col-sm-5 my-auto">
        <img class="d-block w-100 mx-3" src='/media/{{event.postor}}' alt="" style="width: 20vh; border-radius: 2vh;">
      </div>
      <div class="col-sm-7">
        <div class="card-block">
          <p class="card-title">{{event.event_title}}</p>
          <p class="card-desc">{{event.event_description|safe|truncatechars:50 }}</p>
          <br>
          <br>
          <a href="/events/EventDetail/{{event.id}}" class="btn btn-primary">Know More</a>
            <a href="{{event.registration_link}}" class="btn btn-success">Register</a>
        </div>
      </div>
    </div>
  </div>
{%endfor%}
</div>
  {%else%}
  <h3 class="mx-4 my-2">No events right now</h3>
  {%endif%}
</div>

{% if request.session.is_authenticated and request.session.is_priviledged %}
  <div class="addEvent">
    <a href="{% url 'events:add_event' %}" class="btn btn-primary addButton" type="submit">Add Event</a>
  </div>
{% endif %}
{% endblock body %}

templates/events/previousEvents.html
{% extends 'base.html' %}
{% block previousActive %} active {% endblock previousActive %}
{% block head %}
  <style>
  .addButton {
    float: right;
    margin-right: 10%;
    margin-bottom: 5%;
    border-radius: 40px;
    color: black;
    font-weight: bold;
    font-size: 1rem;
  }
  body {
    background-color: #eee;
  }

  .title {

    margin-bottom: 50px;
    text-transform: uppercase;
  }

  .card-block {
    font-size: 1em;
    position: relative;
    margin: 0;
    padding: 1em;
    border: none;
    border-top: 1px solid rgba(34, 36, 38, .1);
    box-shadow: none;

  }

  .card {
    font-size: 1em;
    overflow: hidden;
    padding: 5;
    border: none;
    border-radius: .28571429rem;
    box-shadow: 0 1px 3px 0 #d4d4d5, 0 0 0 1px #d4d4d5;
    margin-top: 20px;
  }
  .card-title {
    font-family: 'Microsoft Sans Serif';
    font-size: 5vh;
    font-weight: bold;
  }
  .card-desc {
    font-size: 5vh; 
  }
  </style>

{% endblock head %}

{% block body %}

{%if events %}
<div class='container-fluid row' >
  {%for event in events %}
  <div class="card text-center mx-auto shadow-lg" style='margin:auto; margin-top:2%; width: 45%; border-radius: 20px;'>
    <div class="row">
      <div class="col-sm-5 my-auto">
        <img class="d-block w-100 mx-3" src='/media/{{event.postor}}' alt="" style="width: 20vh; border-radius: 2vh;">
      </div>
      <div class="col-sm-7">
        <div class="card-block">
          <p class="card-title">{{event.event_title}}</p>
          <p class="card-desc">{{event.event_description|safe|truncatechars:50 }}</p>
          <br>
          <br>
          <a href="/events/EventDetail/{{event.id}}" class="btn btn-primary">Know More</a>
            <a href="{{event.registration_link}}" class="btn btn-success">Register</a>
        </div>
      </div>
    </div>
  </div>
{%endfor%}
</div>
  {%else%}
  <h3 class="mx-4 my-2">No events right now</h3>
  {%endif%}
</div>

{% if request.session.is_authenticated and request.session.is_priviledged %}
  <div class="addEvent">
    <a href="{% url 'events:add_event' %}" class="btn btn-primary addButton" type="submit">Add Event</a>
  </div>
{% endif %}
{% endblock body %}